name: pipeline

on:
  workflow_call:
    inputs:
      # REQUIRED ============================
      version:
        required: true
        type: string
      # OPTIONAL ============================
      bake-convention:
        required: false
        default: 'default'
        type: string
      bake-version:
        required: false
        type: string
        default: '0.30.43-beta'
    secrets:
      nuget-api-key:
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      HELPZ_POSTGRESQL_PASS: Password12!
      EVENTFLOW_MSSQL_SERVER: 127.0.0.1,1433
      EVENTFLOW_MSSQL_USER: sa
      EVENTFLOW_MSSQL_PASS: Password12!
      NUGET_APIKEY: ${{ secrets.nuget-api-key }}

    services:
      rabbitmq:
        image: rabbitmq:3-management-alpine
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672

      eventstore:
        image: eventstore/eventstore:release-4.1.3
        ports:
          - "1113:1113"
          - "2113:2113"

      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password12!
        ports:
          - "5432:5432"

      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password12!
        ports:
          - "1433:1433"

    steps:
    - name: Configure sysctl limits for Elasticsearch
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Run Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 6.8.3

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          8.0.x

    # Yes, EventFlow has a custom built build tool. If you are reading this
    # you might have a better idea of how to do it alternatively, if so,
    # create a PR for EventFlow.

    # https://github.com/rasmus/Bake
    - name: Install Bake 
      run: dotnet tool install -g --version ${{ inputs.bake-version }} Bake 

    - name: Run Bake
      env:
        MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bake run \
          --convention=${{ inputs.bake-convention }} \
          --build-version ${{ inputs.version }} \
          --destination="nuget>github,nuget,release>github"

    - name: Upload NuGet packages
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: packages
        path: "**/*nupkg"
        if-no-files-found: error

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: "**/*.trx"
        if-no-files-found: error
